# Final encoding fix script with exact patterns
param([string]$Path = "content")

$files = Get-ChildItem -Path $Path -Recurse -Filter "*_index.vi.md"
$count = 0

foreach ($file in $files) {
    Write-Host "Processing: $($file.Name)"
    
    $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
    $original = $content
    
    # Exact patterns found in the files
    $content = $content.Replace('CÃ¡c', 'Các')
    $content = $content.Replace('thÃ´ng', 'thông')
    $content = $content.Replace('tin', 'tin')
    $content = $content.Replace('dÆ°á»›i', 'dưới')
    $content = $content.Replace('Ä'Ã¢y', 'đây')
    $content = $content.Replace('chá»‰', 'chỉ')
    $content = $content.Replace('nháº±m', 'nhằm')
    $content = $content.Replace('má»¥c', 'mục')
    $content = $content.Replace('Ä'Ã­ch', 'đích')
    $content = $content.Replace('tham', 'tham')
    $content = $content.Replace('kháº£o', 'khảo')
    $content = $content.Replace('vui', 'vui')
    $content = $content.Replace('lÃ²ng', 'lòng')
    $content = $content.Replace('khÃ´ng', 'không')
    $content = $content.Replace('sao', 'sao')
    $content = $content.Replace('chÃ©p', 'chép')
    $content = $content.Replace('nguyÃªn', 'nguyên')
    $content = $content.Replace('vÄƒn', 'văn')
    $content = $content.Replace('cho', 'cho')
    $content = $content.Replace('bÃ i', 'bài')
    $content = $content.Replace('bÃ¡o', 'báo')
    $content = $content.Replace('cÃ¡o', 'cáo')
    $content = $content.Replace('cá»§a', 'của')
    $content = $content.Replace('báº¡n', 'bạn')
    $content = $content.Replace('ká»ƒ', 'kể')
    $content = $content.Replace('cáº£', 'cả')
    $content = $content.Replace('warning', 'warning')
    $content = $content.Replace('nÃ y', 'này')
    $content = $content.Replace('Káº¿t', 'Kết')
    $content = $content.Replace('ná»'i', 'nối')
    $content = $content.Replace('lÃ m', 'làm')
    $content = $content.Replace('quen', 'quen')
    $content = $content.Replace('vá»›i', 'với')
    $content = $content.Replace('cÃ¡c', 'các')
    $content = $content.Replace('thÃ nh', 'thành')
    $content = $content.Replace('viÃªn', 'viên')
    $content = $content.Replace('trong', 'trong')
    $content = $content.Replace('First', 'First')
    $content = $content.Replace('Cloud', 'Cloud')
    $content = $content.Replace('Journey', 'Journey')
    $content = $content.Replace('Hiá»ƒu', 'Hiểu')
    $content = $content.Replace('dá»‹ch', 'dịch')
    $content = $content.Replace('vá»¥', 'vụ')
    $content = $content.Replace('AWS', 'AWS')
    $content = $content.Replace('cÆ¡', 'cơ')
    $content = $content.Replace('báº£n', 'bản')
    $content = $content.Replace('cÃ¡ch', 'cách')
    $content = $content.Replace('dÃ¹ng', 'dùng')
    $content = $content.Replace('console', 'console')
    $content = $content.Replace('CLI', 'CLI')
    $content = $content.Replace('Thá»©', 'Thứ')
    $content = $content.Replace('CÃ´ng', 'Công')
    $content = $content.Replace('viá»‡c', 'việc')
    $content = $content.Replace('NgÃ y', 'Ngày')
    $content = $content.Replace('báº¯t', 'bắt')
    $content = $content.Replace('Ä'áº§u', 'đầu')
    $content = $content.Replace('hoÃ n', 'hoàn')
    $content = $content.Replace('thÃ nh', 'thành')
    $content = $content.Replace('Nguá»"n', 'Nguồn')
    $content = $content.Replace('tÃ i', 'tài')
    $content = $content.Replace('liá»‡u', 'liệu')
    $content = $content.Replace('LÃ m', 'Làm')
    $content = $content.Replace('FCJ', 'FCJ')
    $content = $content.Replace('Äá»c', 'Đọc')
    $content = $content.Replace('vÃ ', 'và')
    $content = $content.Replace('lÆ°u', 'lưu')
    $content = $content.Replace('Ã½', 'ý')
    $content = $content.Replace('ná»™i', 'nội')
    $content = $content.Replace('quy', 'quy')
    $content = $content.Replace('Ä'á»‹nh', 'định')
    $content = $content.Replace('táº¡i', 'tại')
    $content = $content.Replace('Ä'Æ¡n', 'đơn')
    $content = $content.Replace('vá»‹', 'vị')
    $content = $content.Replace('thá»±c', 'thực')
    $content = $content.Replace('táº­p', 'tập')
    $content = $content.Replace('TÃ¬m', 'Tìm')
    $content = $content.Replace('hiá»ƒu', 'hiểu')
    $content = $content.Replace('loáº¡i', 'loại')
    $content = $content.Replace('Compute', 'Compute')
    $content = $content.Replace('Storage', 'Storage')
    $content = $content.Replace('Networking', 'Networking')
    $content = $content.Replace('Database', 'Database')
    $content = $content.Replace('Táº¡o', 'Tạo')
    $content = $content.Replace('Free', 'Free')
    $content = $content.Replace('Tier', 'Tier')
    $content = $content.Replace('account', 'account')
    $content = $content.Replace('Console', 'Console')
    $content = $content.Replace('Thá»±c', 'Thực')
    $content = $content.Replace('hÃ nh', 'hành')
    $content = $content.Replace('CÃ i', 'Cài')
    $content = $content.Replace('cáº¥u', 'cấu')
    $content = $content.Replace('hÃ¬nh', 'hình')
    $content = $content.Replace('CÃ¡ch', 'Cách')
    $content = $content.Replace('sá»­', 'sử')
    $content = $content.Replace('dá»¥ng', 'dụng')
    $content = $content.Replace('EC2', 'EC2')
    $content = $content.Replace('Instance', 'Instance')
    $content = $content.Replace('types', 'types')
    $content = $content.Replace('AMI', 'AMI')
    $content = $content.Replace('EBS', 'EBS')
    $content = $content.Replace('remote', 'remote')
    $content = $content.Replace('SSH', 'SSH')
    $content = $content.Replace('vÃ o', 'vào')
    $content = $content.Replace('Elastic', 'Elastic')
    $content = $content.Replace('IP', 'IP')
    $content = $content.Replace('instance', 'instance')
    $content = $content.Replace('Káº¿t', 'Kết')
    $content = $content.Replace('ná»'i', 'nối')
    $content = $content.Replace('Gáº¯n', 'Gắn')
    $content = $content.Replace('volume', 'volume')
    $content = $content.Replace('lÃ ', 'là')
    $content = $content.Replace('gÃ¬', 'gì')
    $content = $content.Replace('náº¯m', 'nắm')
    $content = $content.Replace('Ä'Æ°á»£c', 'được')
    $content = $content.Replace('nhÃ³m', 'nhóm')
    $content = $content.Replace('ÄÃ£', 'Đã')
    $content = $content.Replace('cÃ³', 'có')
    $content = $content.Replace('thÃ nh', 'thành')
    $content = $content.Replace('cÃ´ng', 'công')
    $content = $content.Replace('Management', 'Management')
    $content = $content.Replace('biáº¿t', 'biết')
    $content = $content.Replace('tÃ¬m', 'tìm')
    $content = $content.Replace('truy', 'truy')
    $content = $content.Replace('cáº­p', 'cập')
    $content = $content.Replace('tá»«', 'từ')
    $content = $content.Replace('giao', 'giao')
    $content = $content.Replace('diá»‡n', 'diện')
    $content = $content.Replace('web', 'web')
    $content = $content.Replace('Ä'áº·t', 'đặt')
    $content = $content.Replace('trÃªn', 'trên')
    $content = $content.Replace('mÃ¡y', 'máy')
    $content = $content.Replace('tÃ­nh', 'tính')
    $content = $content.Replace('bao', 'bao')
    $content = $content.Replace('gá»"m', 'gồm')
    $content = $content.Replace('Access', 'Access')
    $content = $content.Replace('Key', 'Key')
    $content = $content.Replace('Secret', 'Secret')
    $content = $content.Replace('Region', 'Region')
    $content = $content.Replace('máº·c', 'mặc')
    $content = $content.Replace('Sá»­', 'Sử')
    $content = $content.Replace('Ä'á»ƒ', 'để')
    $content = $content.Replace('thá»±c', 'thực')
    $content = $content.Replace('hiá»‡n', 'hiện')
    $content = $content.Replace('thao', 'thao')
    $content = $content.Replace('tÃ¡c', 'tác')
    $content = $content.Replace('nhÆ°', 'như')
    $content = $content.Replace('Kiá»ƒm', 'Kiểm')
    $content = $content.Replace('tra', 'tra')
    $content = $content.Replace('khoáº£n', 'khoản')
    $content = $content.Replace('Láº¥y', 'Lấy')
    $content = $content.Replace('danh', 'danh')
    $content = $content.Replace('sÃ¡ch', 'sách')
    $content = $content.Replace('region', 'region')
    $content = $content.Replace('Xem', 'Xem')
    $content = $content.Replace('quáº£n', 'quản')
    $content = $content.Replace('lÃ½', 'lý')
    $content = $content.Replace('key', 'key')
    $content = $content.Replace('pair', 'pair')
    $content = $content.Replace('Ä'ang', 'đang')
    $content = $content.Replace('cháº¡y', 'chạy')
    $content = $content.Replace('kháº£', 'khả')
    $content = $content.Replace('nÄƒng', 'năng')
    $content = $content.Replace('giá»¯a', 'giữa')
    $content = $content.Replace('song', 'song')
    $content = $content.Replace('nguyÃªn', 'nguyên')
    
    if ($content -ne $original) {
        Set-Content -Path $file.FullName -Value $content -Encoding UTF8
        Write-Host "  Fixed: $($file.Name)" -ForegroundColor Green
        $count++
    } else {
        Write-Host "  No changes: $($file.Name)" -ForegroundColor Gray
    }
}

Write-Host "Total files fixed: $count" -ForegroundColor Green
