# PowerShell Script to fix Vietnamese encoding errors in _index.vi.md files
# Author: Assistant
# Purpose: Replace all UTF-8 encoding errors with correct Vietnamese characters

param(
    [string]$FolderPath = "content"
)

# List of replacement pairs (encoding error -> correct character)
$replacements = @{
    'Ã¡' = 'á'
    'Ã ' = 'à'
    'áº£' = 'ả'
    'Ã£' = 'ã'
    'áº¡' = 'ạ'
    'Ã¢' = 'â'
    'áº¥' = 'ấ'
    'áº§' = 'ầ'
    'áº©' = 'ẩ'
    'áº«' = 'ẫ'
    'áº­' = 'ậ'
    'Ä' = 'ă'
    'áº¯' = 'ắ'
    'áº±' = 'ằ'
    'áº³' = 'ẳ'
    'áºµ' = 'ẵ'
    'áº·' = 'ặ'
    'Ã©' = 'é'
    'Ã¨' = 'è'
    'áº»' = 'ẻ'
    'áº½' = 'ẽ'
    'áº¹' = 'ẹ'
    'Ãª' = 'ê'
    'áº¿' = 'ế'
    'á»' = 'ề'
    'á»ƒ' = 'ể'
    'á»…' = 'ễ'
    'á»‡' = 'ệ'
    'Ã­' = 'í'
    'Ã¬' = 'ì'
    'á»‰' = 'ỉ'
    'Ä©' = 'ĩ'
    'á»‹' = 'ị'
    'Ã³' = 'ó'
    'Ã²' = 'ò'
    'á»' = 'ỏ'
    'Ãµ' = 'õ'
    'á»' = 'ọ'
    'Ã´' = 'ô'
    'á»'= 'ố'
    'á»"' = 'ồ'
    'á»•' = 'ổ'
    'á»—' = 'ỗ'
    'á»™' = 'ộ'
    'Æ¡' = 'ơ'
    'á»›' = 'ớ'
    'á»' = 'ờ'
    'á»Ÿ' = 'ở'
    'á»¡' = 'ỡ'
    'á»£' = 'ợ'
    'Ãº' = 'ú'
    'Ã¹' = 'ù'
    'á»§' = 'ủ'
    'Å©' = 'ũ'
    'á»¥' = 'ụ'
    'Æ°' = 'ư'
    'á»©' = 'ứ'
    'á»«' = 'ừ'
    'á»­' = 'ử'
    'á»¯' = 'ữ'
    'á»±' = 'ự'
    'Ã½' = 'ý'
    'á»³' = 'ỳ'
    'á»·' = 'ỷ'
    'á»¹' = 'ỹ'
    'á»µ' = 'ỵ'
    'Ä'' = 'đ'
    'CÃ¡c' = 'Các'
    'cÃ¡c' = 'các'
    'TÃ¬m' = 'Tìm'
    'tÃ¬m' = 'tìm'
    'hiá»ƒu' = 'hiểu'
    'Hiá»ƒu' = 'Hiểu'
    'dá»‹ch' = 'dịch'
    'Dá»‹ch' = 'Dịch'
    'vá»¥' = 'vụ'
    'Vá»¥' = 'Vụ'
    'cÃ´ng' = 'công'
    'CÃ´ng' = 'Công'
    'viá»‡c' = 'việc'
    'Viá»‡c' = 'Việc'
    'ngÃ y' = 'ngày'
    'NgÃ y' = 'Ngày'
    'thá»©' = 'thứ'
    'Thá»©' = 'Thứ'
    'tuáº§n' = 'tuần'
    'Tuáº§n' = 'Tuần'
    'má»¥c' = 'mục'
    'Má»¥c' = 'Mục'
    'tiÃªu' = 'tiêu'
    'TiÃªu' = 'Tiêu'
    'káº¿t' = 'kết'
    'Káº¿t' = 'Kết'
    'quáº£' = 'quả'
    'Quáº£' = 'Quả'
    'Ä'áº¡t' = 'đạt'
    'Ä'Æ°á»£c' = 'được'
    'triá»ƒn' = 'triển'
    'Triá»ƒn' = 'Triển'
    'cáº§n' = 'cần'
    'Cáº§n' = 'Cần'
    'thá»±c' = 'thực'
    'Thá»±c' = 'Thực'
    'táº­p' = 'tập'
    'Táº­p' = 'Tập'
    'háº¡n' = 'hạn'
    'Háº¡n' = 'Hạn'
    'thÃ nh' = 'thành'
    'ThÃ nh' = 'Thành'
    'cÃ³' = 'có'
    'CÃ³' = 'Có'
    'lÃ ' = 'là'
    'LÃ ' = 'Là'
    'gÃ¬' = 'gì'
    'GÃ¬' = 'Gì'
    'vÃ ' = 'và'
    'VÃ ' = 'Và'
    'náº¯m' = 'nắm'
    'Náº¯m' = 'Nắm'
    'nhÃ³m' = 'nhóm'
    'NhÃ³m' = 'Nhóm'
    'cÆ¡' = 'cơ'
    'CÆ¡' = 'Cơ'
    'báº£n' = 'bản'
    'Báº£n' = 'Bản'
    'Ä'Ã£' = 'đã'
    'táº¡o' = 'tạo'
    'Táº¡o' = 'Tạo'
    'cáº¥u' = 'cấu'
    'Cáº¥u' = 'Cấu'
    'hÃ¬nh' = 'hình'
    'HÃ¬nh' = 'Hình'
    'cÃ´ng' = 'công'
    'CÃ´ng' = 'Công'
    'lÃ m' = 'làm'
    'LÃ m' = 'Làm'
    'vá»›i' = 'với'
    'Vá»›i' = 'Với'
    'biáº¿t' = 'biết'
    'Biáº¿t' = 'Biết'
    'cÃ¡ch' = 'cách'
    'CÃ¡ch' = 'Cách'
    'cáº­p' = 'cập'
    'Cáº­p' = 'Cập'
    'sá»­' = 'sử'
    'Sá»­' = 'Sử'
    'dá»¥ng' = 'dụng'
    'Dá»¥ng' = 'Dụng'
    'tá»«' = 'từ'
    'Tá»«' = 'Từ'
    'diá»‡n' = 'diện'
    'Diá»‡n' = 'Diện'
    'cÃ i' = 'cài'
    'CÃ i' = 'Cài'
    'Ä'áº·t' = 'đặt'
    'trÃªn' = 'trên'
    'TrÃªn' = 'Trên'
    'mÃ¡y' = 'máy'
    'MÃ¡y' = 'Máy'
    'tÃ­nh' = 'tính'
    'TÃ­nh' = 'Tính'
    'gá»"m' = 'gồm'
    'Gá»"m' = 'Gồm'
    'máº·c' = 'mặc'
    'Máº·c' = 'Mặc'
    'Ä'á»‹nh' = 'định'
    'Ä'á»ƒ' = 'để'
    'hiá»‡n' = 'hiện'
    'Hiá»‡n' = 'Hiện'
    'tÃ¡c' = 'tác'
    'TÃ¡c' = 'Tác'
    'nhÆ°' = 'như'
    'NhÆ°' = 'Như'
    'kiá»ƒm' = 'kiểm'
    'Kiá»ƒm' = 'Kiểm'
    'thÃ´ng' = 'thông'
    'ThÃ´ng' = 'Thông'
    'tÃ i' = 'tài'
    'TÃ i' = 'Tài'
    'khoáº£n' = 'khoản'
    'Khoáº£n' = 'Khoản'
    'láº¥y' = 'lấy'
    'Láº¥y' = 'Lấy'
    'sÃ¡ch' = 'sách'
    'SÃ¡ch' = 'Sách'
    'quáº£n' = 'quản'
    'Quáº£n' = 'Quản'
    'lÃ½' = 'lý'
    'LÃ½' = 'Lý'
    'Ä'ang' = 'đang'
    'cháº¡y' = 'chạy'
    'Cháº¡y' = 'Chạy'
    'kháº£' = 'khả'
    'Kháº£' = 'Khả'
    'nÄƒng' = 'năng'
    'NÄƒng' = 'Năng'
    'giá»¯a' = 'giữa'
    'Giá»¯a' = 'Giữa'
    'nguyÃªn' = 'nguyên'
    'NguyÃªn' = 'Nguyên'
    'LÆ°u' = 'Lưu'
    'lÆ°u' = 'lưu'
    'dÆ°á»›i' = 'dưới'
    'DÆ°á»›i' = 'Dưới'
    'Ä'Ã¢y' = 'đây'
    'chá»‰' = 'chỉ'
    'Chá»‰' = 'Chỉ'
    'kháº£o' = 'khảo'
    'Kháº£o' = 'Khảo'
    'lÃ²ng' = 'lòng'
    'LÃ²ng' = 'Lòng'
    'chÃ©p' = 'chép'
    'ChÃ©p' = 'Chép'
    'vÄƒn' = 'văn'
    'VÄƒn' = 'Văn'
    'bÃ i' = 'bài'
    'BÃ i' = 'Bài'
    'bÃ¡o' = 'báo'
    'BÃ¡o' = 'Báo'
    'cÃ¡o' = 'cáo'
    'CÃ¡o' = 'Cáo'
    'cá»§a' = 'của'
    'Cá»§a' = 'Của'
    'ká»ƒ' = 'kể'
    'Ká»ƒ' = 'Kể'
    'cáº£' = 'cả'
    'Cáº£' = 'Cả'
    'nÃ y' = 'này'
    'NÃ y' = 'Này'
    'ná»™i' = 'nội'
    'Ná»™i' = 'Nội'
    'Ä'á»c' = 'đọc'
    'báº¯t' = 'bắt'
    'Báº¯t' = 'Bắt'
    'Ä'áº§u' = 'đầu'
    'hoÃ n' = 'hoàn'
    'HoÃ n' = 'Hoàn'
    'nguá»"n' = 'nguồn'
    'Nguá»"n' = 'Nguồn'
    'liá»‡u' = 'liệu'
    'Liá»‡u' = 'Liệu'
    'báº£n' = 'bản'
    'Báº£n' = 'Bản'
    'Ä'á»' = 'đề'
    'xuáº¥t' = 'xuất'
    'Xuáº¥t' = 'Xuất'
    'â€"' = '–'
    'âš ï¸' = '⚠️'
}

Write-Host "Starting Vietnamese encoding fix..." -ForegroundColor Green

# Find all _index.vi.md files
$files = Get-ChildItem -Path $FolderPath -Recurse -Filter "*_index.vi.md"

$totalFiles = $files.Count
$processedFiles = 0
$totalReplacements = 0

foreach ($file in $files) {
    $processedFiles++
    Write-Host "[$processedFiles/$totalFiles] Processing: $($file.FullName)" -ForegroundColor Yellow
    
    try {
        $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8
        $originalContent = $content
        $fileReplacements = 0
        
        foreach ($pair in $replacements.GetEnumerator()) {
            $oldValue = $pair.Key
            $newValue = $pair.Value
            
            if ($content.Contains($oldValue)) {
                $beforeCount = ($content.Split($oldValue)).Count - 1
                $content = $content.Replace($oldValue, $newValue)
                $fileReplacements += $beforeCount
                Write-Host "  - Replaced '$oldValue' -> '$newValue' ($beforeCount times)" -ForegroundColor Cyan
            }
        }
        
        if ($content -ne $originalContent) {
            Set-Content -Path $file.FullName -Value $content -Encoding UTF8
            Write-Host "  * Fixed $fileReplacements encoding errors in this file" -ForegroundColor Green
            $totalReplacements += $fileReplacements
        } else {
            Write-Host "  - No encoding errors found in this file" -ForegroundColor Gray
        }
    }
    catch {
        Write-Host "  X Error processing file: $($_.Exception.Message)" -ForegroundColor Red
    }
}

Write-Host "`nCompleted!" -ForegroundColor Green
Write-Host "Total fixed $totalReplacements encoding errors in $totalFiles files." -ForegroundColor Green
Write-Host "Please check the files to ensure everything displays correctly." -ForegroundColor Yellow